### ISSUE TITLE
Config class for DPU cannot contain any non-settable (static) field

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugin-DevEnv#7]
For example even 
private static final long serialVersionUID = -1976290368429585223L;
trigers exception in runtime.
Problem is in ConfigWrap.java:156, there has to be check if field is private non-static.

**Comment by skodape** [comment]
I think this was already been solved in https://github.com/UnifiedViews/Plugin-DevEnv/commit/5fef7fca99679da0e99ebb609abe6e24ab7cd3e1

Maybe 33 refers to Jira? But based on commit's code it looks that similar approach like in cuni-helpers is in used. As, best to my knowledge, we do not face this problem with cuni helpers, it should be ok for core too.

**Comment by skrchnavy** [comment]
UnifiedViews/Core#33 is issue in core.

**Comment by Jan-Marcek** [comment]
Hm, I just wondering...

**Comment by skodape** [comment]
About? This should be solve by check for final fields: 
https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-api-helpers/src/main/java/eu/unifiedviews/helpers/dpu/config/ConfigWrap.java line 231 
or
https://github.com/mff-uk/Plugin-Utils/blob/master/libs/boost-dpu/src/main/java/cz/cuni/mff/xrg/uv/boost/serialization/xml/SerializationXmlImpl.java line 92

Or was the the question about something else?

**Comment by Jan-Marcek** [comment]
Maybe about this.
I don't know why we do this:
1. default = getDefaultConfigration()
2. copy fileds from saved_configuration into the default 
3. return default. 

Maybe I'm missing something..

(really wondering)
I guess, check of serialVersionUID is made during parse and casting config file ...
https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-api-helpers/src/main/java/eu/unifiedviews/helpers/dpu/config/ConfigWrap.java#L139



(you can create link to line directly https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-api-helpers/src/main/java/eu/unifiedviews/helpers/dpu/config/ConfigWrap.java#L231)

**Comment by skodape** [comment]
Thanks for the line-hint.

Well this is kind a old solution connected with some changes in configuration. The idea was to support addition of new fields to the configuration. Scenario:
- I create DPU .. with configuration fields A, B. 
- Over time I add new configuration field C (some additional configuration, check box etc.. )
- Now then I use the new DPU with the old configuration the expected result is, that I got A, B from the configuration stored in database, but as C is missing in database it should be set to it's default.

I'm not sure if this is still true .. but the problem was, that if we use XStream directly, then C was set to null. So we need to do this thing to meet the requirements.

As to a process you mention (those 3 steps I would update it a little):
- load saved_configuration to C1 ( https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-api-helpers/src/main/java/eu/unifiedviews/helpers/dpu/config/ConfigWrap.java#L129 )
  - watch for any missing fields ( https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-api-helpers/src/main/java/eu/unifiedviews/helpers/dpu/config/ConfigWrap.java#L69 )
- now if there some field that has not been set from saved_configuration ( https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-api-helpers/src/main/java/eu/unifiedviews/helpers/dpu/config/ConfigWrap.java#L157 ) we set them from default configuration, as now they are set to null
- in order to do this we call copyFields ( https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-api-helpers/src/main/java/eu/unifiedviews/helpers/dpu/config/ConfigWrap.java#L226 )
- so at the end we get saved_configuration, and field that has not been saved to this configuration are set to the default values (instead of null, as xStream do by default)

Is is answer to you question?
